import { v4 as uuidv4 } from 'uuid';
import { User } from './models/user';
import { Profile } from './models/profile';

const adminProfileId = uuidv4();
const userProfileId = uuidv4();
const guestProfileId = uuidv4();

export const seedProfiles: Profile[] = [
  { id: adminProfileId, name: 'Admin' },
  { id: userProfileId, name: 'User' },
  { id: guestProfileId, name: 'Guest' },
];

export const seedUsers: User[] = [
  {
    id: uuidv4(),
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@example.com',
    isActive: true,
    profileId: adminProfileId,
  },
  {
    id: uuidv4(),
    firstName: 'Sarah',
    lastName: 'Williams',
    email: 'sarah.williams@example.com',
    isActive: true,
    profileId: adminProfileId,
  },
  {
    id: uuidv4(),
    firstName: 'Michael',
    lastName: 'Brown',
    email: 'michael.brown@example.com',
    isActive: true,
    profileId: adminProfileId,
  },
  {
    id: uuidv4(),
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@example.com',
    isActive: true,
    profileId: userProfileId,
  },
  {
    id: uuidv4(),
    firstName: 'Robert',
    lastName: 'Johnson',
    email: 'robert.johnson@example.com',
    isActive: true,
    profileId: userProfileId,
  },
  {
    id: uuidv4(),
    firstName: 'Emily',
    lastName: 'Davis',
    email: 'emily.davis@example.com',
    isActive: true,
    profileId: userProfileId,
  },
  {
    id: uuidv4(),
    firstName: 'David',
    lastName: 'Miller',
    email: 'david.miller@example.com',
    isActive: true,
    profileId: userProfileId,
  },
  {
    id: uuidv4(),
    firstName: 'Jessica',
    lastName: 'Wilson',
    email: 'jessica.wilson@example.com',
    isActive: false,
    profileId: userProfileId,
  },
  {
    id: uuidv4(),
    firstName: 'Christopher',
    lastName: 'Moore',
    email: 'christopher.moore@example.com',
    isActive: true,
    profileId: userProfileId,
  },
  {
    id: uuidv4(),
    firstName: 'Amanda',
    lastName: 'Taylor',
    email: 'amanda.taylor@example.com',
    isActive: true,
    profileId: userProfileId,
  },
  {
    id: uuidv4(),
    firstName: 'Daniel',
    lastName: 'Anderson',
    email: 'daniel.anderson@example.com',
    isActive: true,
    profileId: userProfileId,
  },
  {
    id: uuidv4(),
    firstName: 'Lauren',
    lastName: 'Thomas',
    email: 'lauren.thomas@example.com',
    isActive: true,
    profileId: userProfileId,
  },
  {
    id: uuidv4(),
    firstName: 'Kevin',
    lastName: 'Jackson',
    email: 'kevin.jackson@example.com',
    isActive: false,
    profileId: userProfileId,
  },
  {
    id: uuidv4(),
    firstName: 'Bob',
    lastName: 'Johnson',
    email: 'bob.johnson@example.com',
    isActive: false,
    profileId: guestProfileId,
  },
  {
    id: uuidv4(),
    firstName: 'Alice',
    lastName: 'White',
    email: 'alice.white@example.com',
    isActive: true,
    profileId: guestProfileId,
  },
  {
    id: uuidv4(),
    firstName: 'Charlie',
    lastName: 'Harris',
    email: 'charlie.harris@example.com',
    isActive: true,
    profileId: guestProfileId,
  },
  {
    id: uuidv4(),
    firstName: 'Diana',
    lastName: 'Martin',
    email: 'diana.martin@example.com',
    isActive: false,
    profileId: guestProfileId,
  },
  {
    id: uuidv4(),
    firstName: 'Edward',
    lastName: 'Garcia',
    email: 'edward.garcia@example.com',
    isActive: true,
    profileId: guestProfileId,
  },
  {
    id: uuidv4(),
    firstName: 'Fiona',
    lastName: 'Rodriguez',
    email: 'fiona.rodriguez@example.com',
    isActive: true,
    profileId: guestProfileId,
  },
  {
    id: uuidv4(),
    firstName: 'George',
    lastName: 'Martinez',
    email: 'george.martinez@example.com',
    isActive: true,
    profileId: guestProfileId,
  },
];
